<?php

namespace App\Helpers;

class CountryHelper
{
    public static function getCountries()
    {
        return [
            'AF' => 'Afeganistão',
            'ZA' => 'África do Sul',
            'AL' => 'Albânia',
            'DE' => 'Alemanha',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antártida',
            'AG' => 'Antígua e Barbuda',
            'SA' => 'Arábia Saudita',
            'DZ' => 'Argélia',
            'AR' => 'Argentina',
            'AM' => 'Armênia',
            'AW' => 'Aruba',
            'AU' => 'Austrália',
            'AT' => 'Áustria',
            'AZ' => 'Azerbaijão',
            'BS' => 'Bahamas',
            'BH' => 'Bahrein',
            'BD' => 'Bangladesh',
            'BB' => 'Barbados',
            'BY' => 'Belarus',
            'BE' => 'Bélgica',
            'BZ' => 'Belize',
            'BJ' => 'Benin',
            'BM' => 'Bermudas',
            'BO' => 'Bolívia',
            'BA' => 'Bósnia e Herzegovina',
            'BW' => 'Botsuana',
            'BR' => 'Brasil',
            'BN' => 'Brunei',
            'BG' => 'Bulgária',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'BT' => 'Butão',
            'CV' => 'Cabo Verde',
            'CM' => 'Camarões',
            'KH' => 'Camboja',
            'CA' => 'Canadá',
            'QA' => 'Catar',
            'KZ' => 'Cazaquistão',
            'TD' => 'Chade',
            'CL' => 'Chile',
            'CN' => 'China',
            'CY' => 'Chipre',
            'SG' => 'Singapura',
            'CO' => 'Colômbia',
            'KM' => 'Comores',
            'CG' => 'Congo',
            'CD' => 'Congo (RDC)',
            'KR' => 'Coreia do Sul',
            'KP' => 'Coreia do Norte',
            'CR' => 'Costa Rica',
            'CI' => 'Costa do Marfim',
            'HR' => 'Croácia',
            'CU' => 'Cuba',
            'DK' => 'Dinamarca',
            'DJ' => 'Djibuti',
            'DM' => 'Dominica',
            'EG' => 'Egito',
            'SV' => 'El Salvador',
            'AE' => 'Emirados Árabes Unidos',
            'EC' => 'Equador',
            'ER' => 'Eritreia',
            'SK' => 'Eslováquia',
            'SI' => 'Eslovênia',
            'ES' => 'Espanha',
            'US' => 'Estados Unidos',
            'EE' => 'Estônia',
            'ET' => 'Etiópia',
            'FJ' => 'Fiji',
            'PH' => 'Filipinas',
            'FI' => 'Finlândia',
            'FR' => 'França',
            'GA' => 'Gabão',
            'GM' => 'Gâmbia',
            'GH' => 'Gana',
            'GE' => 'Geórgia',
            'GI' => 'Gibraltar',
            'GR' => 'Grécia',
            'GD' => 'Granada',
            'GL' => 'Groenlândia',
            'GP' => 'Guadalupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernsey',
            'GY' => 'Guiana',
            'GF' => 'Guiana Francesa',
            'GN' => 'Guiné',
            'GQ' => 'Guiné Equatorial',
            'GW' => 'Guiné-Bissau',
            'HT' => 'Haiti',
            'HN' => 'Honduras',
            'HK' => 'Hong Kong',
            'HU' => 'Hungria',
            'YE' => 'Iêmen',
            'BV' => 'Ilha Bouvet',
            'IM' => 'Ilha de Man',
            'CX' => 'Ilha do Natal',
            'NF' => 'Ilha Norfolk',
            'AX' => 'Ilhas Åland',
            'KY' => 'Ilhas Cayman',
            'CC' => 'Ilhas Cocos',
            'CK' => 'Ilhas Cook',
            'FO' => 'Ilhas Faroe',
            'GS' => 'Ilhas Geórgia do Sul e Sandwich do Sul',
            'HM' => 'Ilhas Heard e McDonald',
            'FK' => 'Ilhas Malvinas',
            'MP' => 'Ilhas Marianas do Norte',
            'MH' => 'Ilhas Marshall',
            'UM' => 'Ilhas Menores Distantes dos Estados Unidos',
            'SB' => 'Ilhas Salomão',
            'TC' => 'Ilhas Turks e Caicos',
            'VG' => 'Ilhas Virgens Britânicas',
            'VI' => 'Ilhas Virgens dos EUA',
            'IN' => 'Índia',
            'ID' => 'Indonésia',
            'IR' => 'Irã',
            'IQ' => 'Iraque',
            'IE' => 'Irlanda',
            'IS' => 'Islândia',
            'IL' => 'Israel',
            'IT' => 'Itália',
            'JM' => 'Jamaica',
            'JP' => 'Japão',
            'JE' => 'Jersey',
            'JO' => 'Jordânia',
            'KW' => 'Kuwait',
            'LA' => 'Laos',
            'LS' => 'Lesoto',
            'LV' => 'Letônia',
            'LB' => 'Líbano',
            'LR' => 'Libéria',
            'LY' => 'Líbia',
            'LI' => 'Liechtenstein',
            'LT' => 'Lituânia',
            'LU' => 'Luxemburgo',
            'MO' => 'Macau',
            'MK' => 'Macedônia do Norte',
            'MG' => 'Madagascar',
            'MY' => 'Malásia',
            'MW' => 'Malawi',
            'MV' => 'Maldivas',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MA' => 'Marrocos',
            'MQ' => 'Martinica',
            'MU' => 'Maurício',
            'MR' => 'Mauritânia',
            'YT' => 'Mayotte',
            'MX' => 'México',
            'FM' => 'Micronésia',
            'MZ' => 'Moçambique',
            'MD' => 'Moldova',
            'MC' => 'Mônaco',
            'MN' => 'Mongólia',
            'ME' => 'Montenegro',
            'MS' => 'Montserrat',
            'MM' => 'Myanmar',
            'NA' => 'Namíbia',
            'NR' => 'Nauru',
            'NP' => 'Nepal',
            'NI' => 'Nicarágua',
            'NE' => 'Níger',
            'NG' => 'Nigéria',
            'NU' => 'Niue',
            'NO' => 'Noruega',
            'NC' => 'Nova Caledônia',
            'NZ' => 'Nova Zelândia',
            'OM' => 'Omã',
            'NL' => 'Países Baixos',
            'PW' => 'Palau',
            'PS' => 'Palestina',
            'PA' => 'Panamá',
            'PG' => 'Papua-Nova Guiné',
            'PK' => 'Paquistão',
            'PY' => 'Paraguai',
            'PE' => 'Peru',
            'PN' => 'Pitcairn',
            'PF' => 'Polinésia Francesa',
            'PL' => 'Polônia',
            'PR' => 'Porto Rico',
            'PT' => 'Portugal',
            'KE' => 'Quênia',
            'KG' => 'Quirguistão',
            'KI' => 'Kiribati',
            'GB' => 'Reino Unido',
            'CZ' => 'República Tcheca',
            'DO' => 'República Dominicana',
            'RE' => 'Reunião',
            'RO' => 'Romênia',
            'RW' => 'Ruanda',
            'RU' => 'Rússia',
            'EH' => 'Saara Ocidental',
            'BL' => 'Saint Barthélemy',
            'SH' => 'Santa Helena',
            'LC' => 'Santa Lúcia',
            'MF' => 'Saint Martin',
            'PM' => 'Saint Pierre e Miquelon',
            'VC' => 'São Vicente e Granadinas',
            'KN' => 'São Cristóvão e Nevis',
            'SM' => 'San Marino',
            'ST' => 'São Tomé e Príncipe',
            'SN' => 'Senegal',
            'SL' => 'Serra Leoa',
            'RS' => 'Sérvia',
            'SC' => 'Seychelles',
            'SY' => 'Síria',
            'SO' => 'Somália',
            'LK' => 'Sri Lanka',
            'SZ' => 'Suazilândia',
            'SD' => 'Sudão',
            'SS' => 'Sudão do Sul',
            'SE' => 'Suécia',
            'CH' => 'Suíça',
            'SR' => 'Suriname',
            'SJ' => 'Svalbard e Jan Mayen',
            'TH' => 'Tailândia',
            'TW' => 'Taiwan',
            'TJ' => 'Tajiquistão',
            'TZ' => 'Tanzânia',
            'IO' => 'Território Britânico do Oceano Índico',
            'TF' => 'Territórios Franceses do Sul',
            'CZ' => 'Tchéquia',
            'TL' => 'Timor-Leste',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinidad e Tobago',
            'TN' => 'Tunísia',
            'TM' => 'Turcomenistão',
            'TR' => 'Turquia',
            'TV' => 'Tuvalu',
            'UA' => 'Ucrânia',
            'UG' => 'Uganda',
            'UY' => 'Uruguai',
            'UZ' => 'Uzbequistão',
            'VU' => 'Vanuatu',
            'VA' => 'Vaticano',
            'VE' => 'Venezuela',
            'VN' => 'Vietnã',
            'WF' => 'Wallis e Futuna',
            'ZM' => 'Zâmbia',
            'ZW' => 'Zimbabwe'
        ];
    }

    public static function getCountriesForSelect()
    {
        $countries = self::getCountries();
        
        // Ordenar alfabeticamente ignorando acentos
        uksort($countries, function($a, $b) use ($countries) {
            $nameA = self::removeAccents($countries[$a]);
            $nameB = self::removeAccents($countries[$b]);
            return strcasecmp($nameA, $nameB);
        });
        
        return $countries;
    }
    
    private static function removeAccents($string)
    {
        $accents = [
            'À' => 'A', 'Á' => 'A', 'Â' => 'A', 'Ã' => 'A', 'Ä' => 'A', 'Å' => 'A',
            'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a', 'å' => 'a',
            'È' => 'E', 'É' => 'E', 'Ê' => 'E', 'Ë' => 'E',
            'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e',
            'Ì' => 'I', 'Í' => 'I', 'Î' => 'I', 'Ï' => 'I',
            'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i',
            'Ò' => 'O', 'Ó' => 'O', 'Ô' => 'O', 'Õ' => 'O', 'Ö' => 'O',
            'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o',
            'Ù' => 'U', 'Ú' => 'U', 'Û' => 'U', 'Ü' => 'U',
            'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u',
            'Ç' => 'C', 'ç' => 'c',
            'Ñ' => 'N', 'ñ' => 'n'
        ];
        
        return strtr($string, $accents);
    }
}